services:
  postgres:
    image: postgres:15-alpine
    container_name: catalog_intelligence_postgres
    restart: always
    environment:
      POSTGRES_DB: OH_YEAH_DB
      POSTGRES_USER: OH_YEAH_USER
      POSTGRES_PASSWORD: OH_YEAH_PASSWORD
    ports:
      - "5434:5432"
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: catalog_intelligence_api
    restart: always
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=OH_YEAH_DB
      - DB_USER=OH_YEAH_USER
      - DB_PASSWORD=OH_YEAH_PASSWORD
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local
